### ISSUE TITLE
Methods to authenticate client?

### ISSUE THREAD

**Issue by henix** [kpdyer/fteproxy#176] opened 2015-06-17 07:11 UTC
I want to run an fteproxy on my own VPS, but it seems that anyone who knows the IP and port number can access this fteproxy.

Is there any method to restrict access? eg. username + password / preshared secrets.

I used to think "--key" option is for that purpose: client key must match server key. But after some test, I've found it's not the case.

**Comment by kpdyer** [comment] 2015-06-17 16:52
Interesting. So, does fteproxy essentially ignore the ```--key``` CLI option?

**Comment by henix** [comment] 2015-06-17 17:15
I don't know what's the expected output when I specify `--key`, but I didn't see any related log. This is my test:

server command:

```
sudo fteproxy --mode server --server_ip 0.0.0.0 --server_port 80 --key "D13C9ED7220460AA4E03920413B906F8DB12E72377F339B5E366991C08D3FF27"
```

server output:

```
fteproxy Copyright (C) 2012-2014 Kevin P. Dyer <kpdyer@gmail.com>
    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.

Server ready!
```

client command:

```
fteproxy --server_ip X.X.X.X --server_port 80
```

client output:

```
fteproxy Copyright (C) 2012-2014 Kevin P. Dyer <kpdyer@gmail.com>
    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    
Client ready!
```

And the client works.

**Comment by kpdyer** [comment] 2015-06-17 17:20
That's surprising. The client shouldn't be able to connect without the server-specified key.

I'll attempt to reproduce this issue.

**Comment by henix** [comment] 2015-06-17 17:27
Thanks for your response!

Here is version info:

Server: Ubuntu 15.04, python2.7.9, fteproxy 0.2.19, install from pip
Client: Archlinux, python2.7.10, fteproxy 0.2.19, install from pip

**Comment by orife** [comment] 2015-09-16 13:33
Same issue reproduces for me on windows 10.
Client and server keys don't match and client can connect to server.

**Comment by kpdyer** [comment] 2015-09-17 03:34
Thanks for confirming! This will be fixed in the next release.

**Comment by irdan** [comment] 2015-09-29 03:32
@kpdyer 
For all practical purposes the `--key` option is ignored. Even if a value is passed in, it is never used as a key within libfte or proxyfte.

Whenever a `DfaEncoderObject` is instantiated, an `fte.encrypter.Encrypter` is created and assigned as an instance variable. There are no arguments passed to the `Encrypter` init, so the key is always the hard coded string escaped hex value found in the `init` function.

Fully addressing this issue requires balancing a few factors that I don't have the full context on. I assume that passing the keys into every new `DfaEncoder` is too much work since repeatedly specifying keys will be cumbersome and error prone.

First, there is a `conf.py` in both proxyfte and libfte, which one should be authoritative? Second, what is the preferred encoding of the key? The hard coded key is escaped hex, while the values found in `conf.py` are literal strings. It doesn't look like the key specified in `conf.py` is used anywhere, at least not within libfte or proxyfte.

Once I know what direction you think will work best, I'll put together another PR to get this resolved.

**Comment by kpdyer** [comment] 2015-09-29 15:15
Thanks for the good work @irdan, very cool!

In most cases, the ```DfaEncoderObject``` will only be instantiated once during a program's run. It looks like the real problem is that ```DfaEncoderObject``` doesn't allows keys ```K1``` and ```K2``` to be specified.

I think we should extend the ```DfaEncoderObject``` constructor to allows the keys to be specified, then make sure that we're actually specifying them via fteproxy (e.g., [2].)

[1] https://github.com/kpdyer/libfte/blob/master/fte/encoder.py#L72
[2] https://github.com/kpdyer/fteproxy/blob/master/fteproxy/cli.py#L154

**Comment by irdan** [comment] 2015-09-30 06:24
I believe I've addressed this issue.  I did this in a hurry so there may be a corner case I missed.

**Comment by kpdyer** [comment] 2015-10-01 02:29
It required a few more changes: [1,2].

However, I think this issue is resolved now.

[1] https://github.com/kpdyer/libfte/commit/821bd0e27970165ebae45071d2065e0a53cd7fdf
[2] https://github.com/kpdyer/fteproxy/commit/d2195b8a2d5a25cae05d5b6ac25fabf4edc66143

**Closed by kpdyer** 2015-10-01 02:29 UTC
