### ISSUE TITLE
Debian package signature not verifiable by apt

### ISSUE THREAD

**Issue by kevinoid** [kpdyer/fteproxy#177] opened 2015-09-12 07:38 UTC
When following the installation instructions from https://fteproxy.org/help-server-with-tor in a fresh installation of Debian 8.2 (Jessie), upon reaching step 3, although `sudo apt-get update` completes without error, running `sudo apt-get install fteproxy` results in the following error and prompt:

```
WARNING: The following packages cannot be authenticated!
  fteproxy
Install these packages without verification? [y/N]
```

Although I'm far from an expert in the apt repository internals, my understanding the issue is that although the detached signature for the release file is present at https://fteproxy.org/deb/stable/Release.gpg there is no release file at either https://fteproxy.org/deb/stable/Release or https://fteproxy.org/deb/stable/InRelease to be verified, which leaves Apt unable to verify the Packages file and the package itself.

Thanks,
Kevin

**Comment by kpdyer** [comment] 2015-09-12 19:08
Thanks for the question!

Were you able to successfully execute the following?

```console
$ gpg --keyserver keys.gnupg.net --recv 6B898EE18FBA6390
$ gpg --export 6B898EE18FBA6390 | sudo apt-key add -
```

**Comment by kevinoid** [comment] 2015-09-12 20:35
Thanks for the quick response!

Yes indeed.  Those commands executed without error.  Are you having difficulty reproducing the error?  If so, I could spin up a fresh chroot and script the entire command sequence.

**Comment by kpdyer** [comment] 2015-09-13 01:29
Yeah, it'd be great if you could provide the exact steps to reproduce this error.

**Comment by kevinoid** [comment] 2015-09-13 03:52
Sure thing.  Here's a script which uses `debootstrap` to create a fresh jessie chroot in a directory named `fteproxy-chroot` in the directory in which it is run, then runs the commands from https://fteproxy.org/help-server-with-tor inside the chroot.  If you don't already have `debootstrap` installed on your system, you'll want to run `apt-get install debootstrap` as root before running this script.  Also note that the script must be run as root.

```sh
#!/bin/sh
debootstrap jessie fteproxy-chroot http://ftp.us.debian.org/debian
cat > fteproxy-chroot/root/fteproxy-chroot-script.sh <<CHROOTEDSCRIPT
#!/bin/sh
echo 'deb http://fteproxy.org/deb/ stable/' >> /etc/apt/sources.list
gpg --keyserver keys.gnupg.net --recv 6B898EE18FBA6390
gpg --export 6B898EE18FBA6390 | apt-key add -
apt-get update
apt-get install fteproxy
CHROOTEDSCRIPT
chmod +x fteproxy-chroot/root/fteproxy-chroot-script.sh
exec chroot fteproxy-chroot /root/fteproxy-chroot-script.sh
```

The script will eventually ask if you want to continue, after answering "y" it will present the warning that the fteproxy package cannot be authenticated.

Let me know if you have any issues running the script or if it doesn't produce the error on your system.

**Comment by kpdyer** [comment] 2015-09-13 22:15
Ok. Confirmed. I was able to reproduce using [1].

What's your usecase? Can you install through PyPI [2]? 

[1] https://github.com/holms/vagrant-jessie-box/releases/download/Jessie-v0.1/Debian-jessie-amd64-netboot.box
[2] https://pypi.python.org/pypi/fte

**Comment by kevinoid** [comment] 2015-09-13 22:46
Great!  My usecase is installing using a trusted source.  I treat Tor as security-sensitive and want to ensure (to a reasonable extent) that if I am providing a bridge to targeted users, that my box isn't being used to compromise them.  I can build from git or install using PyPI, but they both add another link in the trust chain (which is probably fine, since GitHub and PyPI are likely trustworthy).  Although with either of those methods, I will have to configure an additional mechanism for automatic updates.

I just assumed that since you included instructions for installing keys into the apt keyring, that you would want to know that it is only partially working.  If you are not concerned about it, feel free to just add a warning to the instruction page so users are aware that the package is not signed.

**Comment by kpdyer** [comment] 2015-09-13 22:50
I'm definitely concerned about it. I just wanted to determine if you have another, reasonable option.

I'll dig deeper into this and try to figure out what's going on. This warning is definitely news to me, and shouldn't be happening.

Also note that I'm trying to get fteproxy officially into the mainstream debian repos. Having my own, unofficial repo. is definitely not ideal.

Thanks for using fteproxy. I'll keep this issue open until the problem is resolved. Unfortunately, I don't have an ETA...

**Comment by kevinoid** [comment] 2015-09-13 22:56
Thanks for looking into it!  No hurry on the fix, I can work around it in the meantime.

**Comment by leggewie** [comment] 2018-04-15 07:48
Closing this ticket since fte has made it into Debian proper.  Verification should no longer be an issue.

**Closed by leggewie** 2018-04-15 07:48 UTC
